### ISSUE TITLE
チュートリアル 33.7 画像処理 | 表の中の誤字 

### ISSUE THREAD

**Issue by polyester-CTRL** [Reputeless/Zenn.Public#11]
「メディアんブラー」( `medianBlur` / `medianBlurred` ) はメディアンブラーの間違いではないでしょうか？

**Comment by Reputeless** [comment]
はい！
Pull-req チャンスを逃さないよう、特にリポジトリで指示されていない場合はいきなり Pull-req 送りましょう。
https://github.com/Reputeless/Zenn.Public/pulls?q=is%3Apr+is%3Aclosed

**Comment by polyester-CTRL** [comment]
Pull-reqを送りました。
