### ISSUE TITLE
チュートリアル 36.16.1のサンプルコードで実行時エラー

### ISSUE THREAD

**Issue by 23tas9** [Reputeless/Zenn.Public#14]
**当該箇所**
`BasicCamera3D camera{ renderTexture.size(), 30_deg, Vec3{ 0, 16, -32 }, Vec3{ 0, 16, -32 } };`
BasicCamera3Dの第3、4引数の位置が一致しているため
エラーメッセージ: Expression: !XMVector3Equal(EyeDirection, XMVectorZero())
が表示される

**解決**
`BasicCamera3D camera{ renderTexture.size(), 30_deg, eyePosition, focusPosition };`

**Comment by Reputeless** [comment]
Fixed. Thanks!
