### ISSUE TITLE
[リファレンス] チュートリアル 17.10 文中の関数名の記述漏れ

### ISSUE THREAD

**Issue by falrnd** [Reputeless/Zenn.Public#2]
https://github.com/Reputeless/Zenn.Public/blame/main/books/siv3d-documentation/tutorial-mouse.md#L261

記載案
* Windows 版では、`Cursor::ClipToWindow(true)` を呼ぶとマウスカーソルが移動できる領域をウィンドウのクライアント領域上に制限できます。制限を解除するには `Cursor::ClipToWindow(false)` を呼びます。
* Windows 版では、`Cursor::ClipToWindow(enable)` を呼ぶとマウスカーソルが移動できる領域をウィンドウのクライアント領域上に制限できます。`true`を渡すと制限が有効に、`false`を渡すと無効になります。

**Comment by Reputeless** [comment]
Fixed. Thank you!
