### ISSUE TITLE
Chapter 65 テクニック | 開発生産性の向上の本文について

### ISSUE THREAD

**Issue by polyester-CTRL** [Reputeless/Zenn.Public#5]
[Chapter 65
テクニック | 開発生産性の向上](https://zenn.dev/reputeless/books/siv3d-documentation/viewer/productivity#1.1-%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0%E3%81%AE%E5%AE%9F%E8%A1%8C%E4%B8%AD%E3%81%AB%E3%82%B3%E3%83%BC%E3%83%89%E3%81%AE%E5%A4%89%E6%9B%B4%E3%82%92%E9%81%A9%E7%94%A8%E3%81%99%E3%82%8B)
リンク先の「Ddebugビルト」というのは「Debugビルド」の間違いではないですか？

**Comment by Reputeless** [comment]
FIxed. Thanks!
