### ISSUE TITLE
チュートリアル 31.7 変数の位置について

### ISSUE THREAD

**Issue by ritsuxis** [Reputeless/Zenn.Public#6]
https://github.com/Reputeless/Zenn.Public/blame/main/books/siv3d-documentation/tutorial-scene-manager.md#L720-L724

`m_exitTransition`と`m_rankingTransition`の宣言位置を逆にしたほうが分かりやすくないでしょうか。

**Comment by Reputeless** [comment]
Fixed. Thanks!
