### ISSUE TITLE
チュートリアル16.6 | サンプル文字抜けについて

### ISSUE THREAD

**Issue by 23tas9** [Reputeless/Zenn.Public#7]
サンプルコード及びサンプル画像の
"[←]/[A] [→][D] [Space]/[W]"
の部分の"[→]"と"[D]"の間の"/"が抜けています。

誤: "[←]/[A] [→][D] [Space]/[W]"
正: "[←]/[A] [→]/[D] [Space]/[W]"

**Comment by Reputeless** [comment]
Fixed. Thanks!
