### ISSUE TITLE
[リファレンス] チュートリアル 35.3 サンプルコード中の変数名の誤字

### ISSUE THREAD

**Issue by falrnd** [Reputeless/Zenn.Public#8]
チュートリアル 35 | 2D カスタムシェーダ｜Siv3D リファレンス v0.6.3
https://zenn.dev/reputeless/books/siv3d-documentation/viewer/tutorial-shader2d#35.3-%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E3%82%B7%E3%82%A7%E3%83%BC%E3%83%80%E3%82%92%E9%81%A9%E7%94%A8%E3%81%99%E3%82%8B

Textureの変数名がtexureになっています。(宣言と呼び出し1カ所で)

**Comment by Reputeless** [comment]
Fixed. Thank you!
